### ISSUE TITLE
Disable building of static libraries per default

### ISSUE THREAD

**Issue by jonte** [Pelagicore/meta-bistro#50]
Poky recently moved to disabling static libraries per default. I think we should investigate the benefits from this, and see if we want to follow their example.

Quote from Poky release notes: 

> Static library generation, for most cases, is now disabled by default in the Poky distribution. Disabling this generation saves some build time as well as the size used for build output artifacts.
>
> Disabling this library generation is accomplished through a meta/conf/distro/include/no-static-libs.inc, which for those not using the Poky distribution can easily include to enable the same functionality.
>
> Any recipe that needs to opt-out of having the "--disable-static" option specified on the configure command line either because it is not a supported option for the configure script or because static libraries are needed should set the following variable:
>
>     DISABLE_STATIC = ""

Full release notes here: http://www.yoctoproject.org/docs/2.1/ref-manual/ref-manual.html#moving-to-the-yocto-project-2.1-release

**Comment by GordanM** [comment]
Since we removed bistro as distro and now PELUX is using poky as a base, this also applies to our releases and as such this issue can be closed. 

`poky/meta-poky/conf/distro/poky.conf:require conf/distro/include/no-static-libs.inc` is included here https://github.com/Pelagicore/meta-pelux/blob/master/conf/distro/pelux.conf#L5 .
